#..................... 
#!.......................[...Project---1...].......................

#TODO: Creating a tool to print band name using city and pet name!.....
#?...Here we are greeting user with welcome message.....
print("Welcome to The Band Name Generator.") 

#?...Ask the user for the city that they grew up in....
city_name = input("What's name of the city you grew up in?\n ") 

#?...Ask the user for the name of a pet.....
pet_name = input("What's your pet's name?\n")

#!...Combining the name of their city and pet and showing them their band name...
print("Your band name could be: " + city_name  + " " + pet_name)