#..................... 
#!.......................[...Project---4...].......................
#TODO: Creating a tool to calculate the tip and split the bill!.....
#?..Taking the input from the users by asking there bill value
#!...printing as welcome message for user
message="Welcome to the tip calculator."
print (message)
#!......taking inputs from the user..........
bill=float(input("What was the total bill? ₹"))
people=int(input("How many people to split the bill? "))
#!.......Formula..........
bill_per_person = bill / people
final_amount = round(bill_per_person, 2)
#!.......Now using formate function to print 2 decimal degit in output.....
final_amount = "{:.2f}".format(bill_per_person)
print (f"Each person should pay: ₹{final_amount}")