#.....
#!.........................[...Project--2...].........................
#TODO:...TO MAKE A BMI CALCULATOR........
#?...Taking imput from the user about there height & weight and then giving them their BMI...

#!...The height should be a "FLOAT" always as it is in meters.....
height = (input("What is your height in (m): "))
#!...The weight should be a "INT" always as it is in kg
weight = (input("What is your weight in (Kg): "))

#TODO::....Declaring weight and height as float and int........
weight_as_int = int(weight)
height_as_float = float(height)
#?...FORMULA......
bmi =weight_as_int/height_as_float**2

#!...AS we need BMI in hole number thatswhy using BMI as "INT"
bmi_as_int = float(bmi)
print("Your BMI is:",bmi_as_int)
