#........
#Todo: Counting the number of character in any names...
#!..firstley we will declare a variable...
num_char = len(input("What is your name? "))

#!now putting the "num_char"Variable into a string...
num_char = str(num_char)  #?...always put the int variable into string to declare both variable and string together..... 

#!Now we will declare a variable and print the output...
print("Your name has " + num_char + " characters")
                                      
                                         